# Generated by Django 4.2.6 on 2023-12-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_alter_information_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='email',
            new_name='to_email',
        ),
    ]
