# Generated by Django 4.2.6 on 2023-12-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_rename_email_information_to_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='to_email',
            field=models.CharField(max_length=100),
        ),
    ]
