# Generated by Django 4.2.6 on 2023-12-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_alter_information_to_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
