# Generated by Django 4.2.6 on 2023-12-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_alter_information_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='to_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
