# Generated by Django 4.2.6 on 2023-12-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0007_alter_information_to_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='to_email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
